### ISSUE TITLE
评测

### ISSUE THREAD

**Issue by cmemec** [MarichMarck/laravel-lmsail#4]
运行了一下，问题较多。
后台laravel-admin集成，也觉得不自在
不知道作者是否还在维护更新

**Comment by lmsail** [comment]
> 运行了一下，问题较多。
> 后台laravel-admin集成，也觉得不自在
> 不知道作者是否还在维护更新

几年前写的项目了，已经不做维护了，可以只使用动态模块，其他模块隐藏掉，用作自己日常记录也还是不错的！
